### ISSUE TITLE
Can't install PyTorch3D with Github actions

### ISSUE THREAD

**Issue by andrewharp** [facebookresearch/pytorch3d#1810]
## 🐛 Bugs / Unexpected behaviors
I can install pytorch3d locally (in a fresh pip env (edit: provided by conda, important later)) if I do this:
```
pip install torch==2.2.0
pip install git+https://github.com/facebookresearch/pytorch3d.git@f34104cf6ebefacd7b7e07955ee7aaa823e616ac
```
However the same operations fail when run in the context of a Github action:

```
        File "/tmp/pip-build-env-1a4p2xfk/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 15, in <module>
      ModuleNotFoundError: No module named 'torch'
```

## Instructions To Reproduce the Issue:

Put the following in .github/workflows as a .yaml file (and change the branch name if necessary):

```yaml
name: Test Pytorch3d

on:
  push:
    branches: [ dev ]
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install pytorch3d
      run: |
        pip install torch==2.2.0
        pip install git+https://github.com/facebookresearch/pytorch3d.git@f34104cf6ebefacd7b7e07955ee7aaa823e616ac
```

Links:
[Failing action .yaml](https://github.com/andrewharp/ComfyUI-EasyNodes/blob/dev/.github/workflows/pytorch.yml)
[Failed run](https://github.com/andrewharp/ComfyUI-EasyNodes/actions/runs/9433878379/job/25985321548)

Even though I install torch first, and then pytorch3d, pytorch3d's setup can't find torch. It doesn't matter if I install them in the same command either.

This seems related to [#1673](https://github.com/facebookresearch/pytorch3d/issues/1673) and [#1419](https://github.com/facebookresearch/pytorch3d/issues/1419) which prevents PyTorch3D from being installed under Poetry due to the installer expecting torch to be present but no mention of the dependency being found in the package info.

Every other combination that I've tried including Pytorch3d fails; I'm not sure how to work around this short of forking pytorch3d and inserting a dependency on torch to keep pip from getting confused.

**Comment by andrewharp** [comment]
I see that [this comment](https://github.com/facebookresearch/pytorch3d/issues/1419#issuecomment-1876033807) says that you can use a prebuilt whl with explicit torch and pytorch3d versions, however I haven't yet been able to find an index of them.

[INSTALL.md](https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md) only mentions prebuilt binaries for PyTorch 1.11.0; is this information current or do additional builds for later PyTorch and Python versions exist?

**Comment by andrewharp** [comment]
I've also tried conda, but it doesn't look like the PyTorch3D conda package supports PyTorch 2.2.0. 

[workflow](https://github.com/andrewharp/ComfyUI-EasyNodes/blob/dev/.github/workflows/test_conda_pytorch3d.yml)
[Failed run](https://github.com/andrewharp/ComfyUI-EasyNodes/actions/runs/9434715340/job/25987177704)

**Comment by andrewharp** [comment]
I tried combining conda+pip and managed to get it to [work](https://github.com/andrewharp/ComfyUI-EasyNodes/actions/runs/9435130781/job/25988139614) with my desired Python+PyTorch versions. I was using Conda on my local machine but not on GitHub initially (just used the default python env), so this could start to explain the difference in behavior.

If anybody else runs into similar problems, try something like this:
```
name: Test Pytorch3d with Conda

on:
  push:
    branches: [ dev ]
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.10'
        activate-environment: myenv
        auto-activate-base: false

    - name: Install dependencies
      run: |
        pip install torch==2.2.0
        pip install git+https://github.com/facebookresearch/pytorch3d.git@stable
        
    - name: Check versions
      run: |
        python -c "import pytorch3d; print(pytorch3d.__version__)"
```

Still not sure if the difference in behavior is expected, so will leave this open.
